/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CloserRouteImport } from './routes/closer'
import { Route as FieldRouteImport } from './routes/field'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HouseRouteImport } from './routes/house'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as MathRouteImport } from './routes/math'
import { Route as PacketRouteImport } from './routes/packet'
import { Route as RoomRouteImport } from './routes/room'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as BeingsBeingIdRouteImport } from './routes/beings.$beingId'
import { Route as CloserBeingIdRouteImport } from './routes/closer.$beingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloserRoute = CloserRouteImport.update({
  id: '/closer',
  path: '/closer',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketRoute = PacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const BeingsBeingIdRoute = BeingsBeingIdRouteImport.update({
  id: '/beings/$beingId',
  path: '/beings/$beingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CloserBeingIdRoute = CloserBeingIdRouteImport.update({
  id: '/$beingId',
  path: '/$beingId',
  getParentRoute: () => CloserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closer': typeof CloserRouteWithChildren
  '/field': typeof FieldRoute
  '/health': typeof HealthRoute
  '/house': typeof HouseRoute
  '/ledger': typeof LedgerRoute
  '/math': typeof MathRoute
  '/packet': typeof PacketRoute
  '/room': typeof RoomRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/beings/$beingId': typeof BeingsBeingIdRoute
  '/closer/$beingId': typeof CloserBeingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closer': typeof CloserRouteWithChildren
  '/field': typeof FieldRoute
  '/health': typeof HealthRoute
  '/house': typeof HouseRoute
  '/ledger': typeof LedgerRoute
  '/math': typeof MathRoute
  '/packet': typeof PacketRoute
  '/room': typeof RoomRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/beings/$beingId': typeof BeingsBeingIdRoute
  '/closer/$beingId': typeof CloserBeingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closer': typeof CloserRouteWithChildren
  '/field': typeof FieldRoute
  '/health': typeof HealthRoute
  '/house': typeof HouseRoute
  '/ledger': typeof LedgerRoute
  '/math': typeof MathRoute
  '/packet': typeof PacketRoute
  '/room': typeof RoomRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/beings/$beingId': typeof BeingsBeingIdRoute
  '/closer/$beingId': typeof CloserBeingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/closer'
    | '/field'
    | '/health'
    | '/house'
    | '/ledger'
    | '/math'
    | '/packet'
    | '/room'
    | '/terms'
    | '/vault'
    | '/beings/$beingId'
    | '/closer/$beingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/closer'
    | '/field'
    | '/health'
    | '/house'
    | '/ledger'
    | '/math'
    | '/packet'
    | '/room'
    | '/terms'
    | '/vault'
    | '/beings/$beingId'
    | '/closer/$beingId'
  id:
    | '__root__'
    | '/'
    | '/closer'
    | '/field'
    | '/health'
    | '/house'
    | '/ledger'
    | '/math'
    | '/packet'
    | '/room'
    | '/terms'
    | '/vault'
    | '/beings/$beingId'
    | '/closer/$beingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloserRoute: typeof CloserRouteWithChildren
  FieldRoute: typeof FieldRoute
  HealthRoute: typeof HealthRoute
  HouseRoute: typeof HouseRoute
  LedgerRoute: typeof LedgerRoute
  MathRoute: typeof MathRoute
  PacketRoute: typeof PacketRoute
  RoomRoute: typeof RoomRoute
  TermsRoute: typeof TermsRoute
  VaultRoute: typeof VaultRoute
  BeingsBeingIdRoute: typeof BeingsBeingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closer': {
      id: '/closer'
      path: '/closer'
      fullPath: '/closer'
      preLoaderRoute: typeof CloserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet': {
      id: '/packet'
      path: '/packet'
      fullPath: '/packet'
      preLoaderRoute: typeof PacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beings/$beingId': {
      id: '/beings/$beingId'
      path: '/beings/$beingId'
      fullPath: '/beings/$beingId'
      preLoaderRoute: typeof BeingsBeingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closer/$beingId': {
      id: '/closer/$beingId'
      path: '/$beingId'
      fullPath: '/closer/$beingId'
      preLoaderRoute: typeof CloserBeingIdRouteImport
      parentRoute: typeof CloserRoute
    }
  }
}

interface CloserRouteChildren {
  CloserBeingIdRoute: typeof CloserBeingIdRoute
}

const CloserRouteChildren: CloserRouteChildren = {
  CloserBeingIdRoute: CloserBeingIdRoute,
}

const CloserRouteWithChildren =
  CloserRoute._addFileChildren(CloserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloserRoute: CloserRouteWithChildren,
  FieldRoute: FieldRoute,
  HealthRoute: HealthRoute,
  HouseRoute: HouseRoute,
  LedgerRoute: LedgerRoute,
  MathRoute: MathRoute,
  PacketRoute: PacketRoute,
  RoomRoute: RoomRoute,
  TermsRoute: TermsRoute,
  VaultRoute: VaultRoute,
  BeingsBeingIdRoute: BeingsBeingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
